### ISSUE TITLE
epub.qlgenerator no longer works. Any chance of an update?

### ISSUE THREAD

**Issue by soundsgoodtome** [GenjiApp/EPUB-Plugins#2]
epub.qlgenerator no longer works. macOS Monterey 12.1 says an update is required. 

It's such a useful plug-in. Any chance of an update?

**Comment by GenjiApp** [comment]
I fixed codes. You can build plug-ins by yourself. However, the binaries are not ready yet.
Thanks.

**Comment by soundsgoodtome** [comment]
Thanks for the reply. I have no clue how to build plug-ins, if that's what you're suggesting. I look forward to your new binaries.

**Comment by GenjiApp** [comment]
I added plug-ins binaries to release page. Please check whether they work.

**Comment by soundsgoodtome** [comment]
Thanks! I installed the new EPUB.qlgenerator, but I still get the following message. I'm not sure if a restart is requried, but after installation I performed one to be safe.

<img width="260" alt="Screen Shot 2021-12-04 at 10 07 28 pm" src="https://user-images.githubusercontent.com/1616664/144735879-bed66bf2-1354-4be6-ae51-3806a629e1a0.png">

**Comment by GenjiApp** [comment]
When was the message panel displayed?

In General pane in Security & Privacy System Preferences Window, is there a button & message that allows plug-in to work?
(the button & message may be displayed at red area shown in attached image)

<img width="334" alt="security_and_privacy" src="https://user-images.githubusercontent.com/904722/144744155-47277599-4fc8-4144-bc8a-7436ea4353d2.png">

**Comment by soundsgoodtome** [comment]
The message that I posted above is displayed the first time I attempt to use Quick Look on an epub file.

No, there is no button or message in the General pane of Security & Privacy.

<img width="668" alt="Screen Shot 2021-12-05 at 8 55 34 am" src="https://user-images.githubusercontent.com/1616664/144755812-b6dca4eb-779f-4766-bcc1-8a2743f43874.png">

**Comment by GenjiApp** [comment]
I think this issue is related Gatekeeper (macOS's security feature). See https://support.apple.com/en-us/HT202491
Its basic solution is to get the notarization from Apple. I investigating how to get the notarization.

**Comment by GenjiApp** [comment]
I added EPUB_notarized.qlgenerator.zip to release page. Try it.

**Comment by soundsgoodtome** [comment]
Thanks!! With the latest version, I am no longer getting the error message.

With some EPUBs, I'm now able to scroll through the contents as expected, which is great! But with others, I only get a thumbnail of the cover. (Screenshot below.) Is there a reason why the plug-in works on some EPUBs but not others?
<img width="580" alt="Screen Shot 2021-12-06 at 8 08 10 am" src="https://user-images.githubusercontent.com/1616664/144881034-bb83bc6d-68ff-44d7-8cf5-b5733ac404d9.png">

**Comment by GenjiApp** [comment]
I don't know now. This problem may be by a bug of plugin, or may be by a bug of your EPUBs.
If your EPUBs, that are not shown their contents by Quick Look, are able to download for free, tell me where to get them.

**Comment by soundsgoodtome** [comment]
Maybe that's the difference: The ones that are free vs. the ones that are purchased. I'm not sure. 

If I find a free one that isn't fully displayed, I'll let you know.

Thanks again. 😊

**Comment by goodoldtime** [comment]
Works excellent on Monterey 12.1! No issues. Is there any chance to have EPUB-MDImporter and QLGenerator  for macOS CATALINA? Since it works on Monterey maybe it needs just few changes to make it work also on CATALINA? It is really a very very useful plug-in!

**Comment by GenjiApp** [comment]
I can't because I'm no longer have Catalina mac machine.

**Comment by goodoldtime** [comment]
Do you know any other plugin, application or work around for CATALINA which allows a quicklook like your plugin? I cannot upgrade my machine to Monterey.

**Comment by GenjiApp** [comment]
I remember that:
- Catalina may have iBooks.qlgenerator in /Library/QuickLook or /System/Library/QuickLook.
- It prevents my plugin loading.
- We cannot delete iBooks.qlgenerator in ordinary way.

**Comment by bobodoll131** [comment]
> Do you know any other plugin, application or work around for CATALINA which allows a quicklook like your plugin? I cannot upgrade my machine to Monterey.

Just tested this. Removing iBooks.qlgenerator from /System/Library/QuickLook does allow the 1.0 plugin to function on Catalina, but not 1.1 or 1.1.1. No idea why- why would only the oldest version be compatible with Catalina, and not the latest supposedly compatible version (1.1.1)? Instructions as follows:

1. Disable System Integrity Protection by running "csrutil disable" in a Recovery Mode terminal window. Restart.
2. Run "sudo mount -uw /" to mount the system partition.
3. Enter "cd /System/Library/QuickLook", then "sudo rm -r iBooks.qlgenerator" to remove the iBooks.qlgenerator in a not ordinary way.
4. If you haven't already, download Genji's EPUB.qlgenerator and run "sudo xattr -r -d com.apple.quarantine /path/to/EPUB.qlgenerator" to remove any quarantine flags. If you have BetterZipQL installed, rename EPUB.qlgenerator to come before the conflicting plugin alphabetically. Move the plugin to /Library/QuickLook or ~/Library/QuickLook depending on your personal preferences.
5. Reset QuickLook with "qlmanage -r"
6. Repeat Step 4 to install EPUB.mdimporter. Run "mdimport -r /path/to/epub.mdimporter" afterwards to have Spotlight begin indexing your EPUB files.
7. Return to Recovery Mode and reenable SIP via "csrutil enable". Restart.

Note that every major system update will reinstall all Apple defaults, including Books.app and the associated iBooks.qlgenerator. So you'll need to repeat the above procedure, if you find it worthwhile.

**Comment by goodoldtime** [comment]
@GenjiApp
Finally I updated from Catalina to Monterey.  Your epub plugin is just wonderful! Thank you very much for the excellent work! One proposal: A kind of dark mode for the quicklook plugin, so that the white background colour gets less bright and less tiring for the eyes when reading text. Anyway: Thank you!!!

**Comment by steveparry1** [comment]
I'm running Big Sur 11.7.2 (on a MacBook Pro M1). I put Epub.qlgenerator 1.1.3 in HD/Library/Quicklook and it didn't work... Binned it, replaced it with 1.1.1 restarted and it didn't work. Any help out there?

**Comment by GenjiApp** [comment]
EPUB.qlgenerator v1.1.2 or later support only macOS 12 or later. Update your Mac. Or, build it yourself.

**Comment by steveparry1** [comment]
Thank you. I have now updated to OS Ventura. I installed the two plugins. Pressing the space bar on an epub file produced the desired preview which looked great on several files! Then I tried it again later and it now only shows an image of the cover :(  I also Reset QuickLook using "qlmanage -r"  in Terminal. Should I do something else?

**Comment by GenjiApp** [comment]
Are all of your EPUBs not previewed only cover, or some of those?
If all EPUBs not previewed: Try to reboot your mac, or run "qlmanage -r", or run "qlmanage -r cache".
If only some EPUBs not shown previewed: It may be a bug of plugin, or may be bug of EPUBs. If these EPUBs obtainable for me, tell me the URL.

**Comment by steveparry1** [comment]
I ran "qlmanage -r cache" in Terminal and restarted. All epubs are only cover image. I get some open source from https://standardebooks.org  I have a Kobo Libra ebook reader so often, but not always, download the kepub.epub version for better viewing on it.

**Comment by GenjiApp** [comment]
I tried to preview some epubs downloaded from standardebooks.org. The results are fine on compatible epub, kepub and advanced epub (however, on kepub and advenced epub were not shown thumbnail icons).

Did you install other epub plugins? If so, uninstall the other plugins.

**Comment by steveparry1** [comment]
I think I just deleted the previous plugins... Would this leave some files in obscure locations and prevent the Genji ones that I replaced them with from loading?

**Comment by GenjiApp** [comment]
run "qlmanage -m plugins | grep epub" and tell me its output.
if there is EPUB.qlmanager in the output, my plugin is loaded normally.
if there is not EPUB.qlmanager, my plugin is not loaded.

if there is other plugin's name, the other plugin prevent to load my plugin. Remove it.

**Comment by steveparry1** [comment]
Thanks for your help. This is the output:

Last login: Fri Jan  6 15:09:21 on console
steveparry@Steves-MacBook-Pro-2 ~ % qlmanage -m plugins | grep epub
  org.idpf.epub-container -> /Applications/BookReader.app/Contents/Library/QuickLook/eBookQuickLook.qlgenerator (1.0.1)
  com.apple.ibooks.epub -> /Library/QuickLook/EPUB.qlgenerator (5)
steveparry@Steves-MacBook-Pro-2 ~ %

**Comment by GenjiApp** [comment]
BookReader.app's plugin is loaded on your system. It prevents to load my plugin (Only one plugin is loaded). Delete the app or delete the plugin in the app. Then, run "qlmanage -r" / "qlmanager -r cache" or reboot.

**Comment by steveparry1** [comment]
Hallelujah!  Most of the epubs and kepubs now scroll with the full text visible! However... all the kepubs I downloaded from https://standardebooks.org/  have lost their cover image both in the finder view and Quicklook preview. The covers were previously visible.

**Comment by GenjiApp** [comment]
Download "Compatible epub" from standardbooks.org. It will be shown icon thumbnails and previews.

I will investigate why kepub version isn't shown icon thumbnails.

**Comment by steveparry1** [comment]
Thank you.

**Comment by steveparry1** [comment]
I wanted to update the plugin on my MBPro running Sonoma 14.2.1  But I cannot see /Library/QuickLook in the Finder. Any ideas how to fix? Also I cannot preview Kepubs - is there a solution for this? Thank you.

**Comment by GenjiApp** [comment]
> But I cannot see /Library/QuickLook in the Finder.

In my Sonoma 14.3 environment, I can find /Library/QuickLook folder.

What happens when you perform the following steps?
- Open Finder
- Click "Go" menu and "Go to Folder..."
- Input "/Library/QuickLook" and press Enter key

Or, you can put a plugin at ~/Library/QuickLook folder.

**Comment by steveparry1** [comment]
Thank you - that worked! I see that I have QLGenerator v1.1.3  in there. That seems to be the latest release. Kepubs don't work in Quicklook though.

**Comment by steveparry1** [comment]
Genji, I made an error of some kind - my apologies. The files I was trying to Quicklook had the wrong file suffix applied to them. I think the suffix was .kepub   They cannot be Quicklooked. I just tested some new epubs that I converted using Patrick Gaskin's wonderful Kepubify engine - the web version: https://pgaskin.net/kepubify/try/  They preview fine and their suffix is .kepub.epub   I think I did something in Calibre previously that messed up the file names somehow, not sure what. I don't like using Calibre to convert epubs because it uses a strange UI that is non-standard for Mac OS. That said; the ability to download covers from the web is very useful. And the ability to convert from .mobi to .kepub.epub is useful. But all's well that ends well.

**Comment by GenjiApp** [comment]
OK. A plugin works well, isn't it?

**Comment by steveparry1** [comment]
Yes it works well. And I presume, being your latest version, it works on files up to 50Mb. Is that correct?

**Comment by GenjiApp** [comment]
Yes.

**Comment by jhzzzzz** [comment]
> > Do you know any other plugin, application or work around for CATALINA which allows a quicklook like your plugin? I cannot upgrade my machine to Monterey.
> 
> Just tested this. Removing iBooks.qlgenerator from /System/Library/QuickLook does allow the 1.0 plugin to function on Catalina, but not 1.1 or 1.1.1. No idea why- why would only the oldest version be compatible with Catalina, and not the latest supposedly compatible version (1.1.1)? Instructions as follows:
> 
>     1. Disable System Integrity Protection by running "csrutil disable" in a Recovery Mode terminal window. Restart.
> 
>     2. Run "sudo mount -uw /" to mount the system partition.
> 
>     3. Enter "cd /System/Library/QuickLook", then "sudo rm -r iBooks.qlgenerator" to remove the iBooks.qlgenerator in a not ordinary way.
> 
>     4. If you haven't already, download Genji's EPUB.qlgenerator and run "sudo xattr -r -d com.apple.quarantine /path/to/EPUB.qlgenerator" to remove any quarantine flags. If you have BetterZipQL installed, rename EPUB.qlgenerator to come before the conflicting plugin alphabetically. Move the plugin to /Library/QuickLook or ~/Library/QuickLook depending on your personal preferences.
> 
>     5. Reset QuickLook with "qlmanage -r"
> 
>     6. Repeat Step 4 to install EPUB.mdimporter. Run "mdimport -r /path/to/epub.mdimporter" afterwards to have Spotlight begin indexing your EPUB files.
> 
>     7. Return to Recovery Mode and reenable SIP via "csrutil enable". Restart.
> 
> 
> Note that every major system update will reinstall all Apple defaults, including Books.app and the associated iBooks.qlgenerator. So you'll need to repeat the above procedure, if you find it worthwhile.

@bobodoll131 : is it possible to have a little bit more detailed description of the required steps?
I've disabled the system protection in the recovery terminal, then I have rebooted.
And at this step, I am stuck.
If I boot normally the Mac (I'm under Big Sur), I cannot mount the / partition :
$ sudo mount -uw /                                                                                                        
Password:
mount_apfs: volume could not be mounted: Permission denied
mount: / failed with 66
$
And if I reboot in recovery, the "mount -uw /" command  doesn't complain (I had to omit 'sudo' as it is not found in the recovery terminal) but there is no QuickLook folder in "/System/Library".

So, in which context is it possible to mount the '/' partition in read/write to be able to delete the undesired qlgenerator?

Thanks in advance.
